### PR TITLE
Show help on missing args for kurma create

### PR DESCRIPTION
**Pull request by wallyqs**
Minor bug fix for `kurma create`

@krobertson @jpoler

### CODE REVIEW

**Comment by jpoler** [comment]
LGTM on green.

**Comment by mbhinder** [comment]
There's nothing built into cobra for arg validation?

**Comment by krobertson** [comment]
I don't know cobra all that well... but the create function had multiple modes of operation. Would like to simplify it some. Need to revive the "kurma cli design document", perhaps for tomorrow's meeting.

**Comment by krobertson** [comment]
LGTM2.

**Comment by wallyqs** [comment]
re: cobra args len handling seems to be still delegated to the user, e.g. by using a switch for example: https://github.com/spf13/cobra/blob/9a8186dbb51a58b06720d2189657fa8adc12f1a1/cobra/cmd/init.go#L48

**Pull request merged**
